### ISSUE TITLE
new captcha images 

### ISSUE THREAD

**Issue by YusaGozlukAdam** [MainSilent/Impulse#9]
do you will add new captcha images? here some example 
![image](https://user-images.githubusercontent.com/91406422/183089921-09912fb8-cda0-4f08-9d80-e1f0de26403e.png)
![image](https://user-images.githubusercontent.com/91406422/183089967-b4b1858a-f9a8-405b-9185-9251097eafac.png)

**Comment by MainSilent** [comment]
It's very time consuming to train a model, As of now I'm not able to spend that time on this project.

**Comment by YusaGozlukAdam** [comment]
@MainSilent so can i add more images to this script? if yes where file i can add images?
